# Generated by Django 3.2.8 on 2021-10-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ad_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='ad',
            name='name',
            field=models.CharField(default='Ad name', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Ad name', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='Ad name', max_length=100),
        ),
    ]
