# Generated by Django 3.2.8 on 2021-10-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_archiveads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_archive',
            field=models.BooleanField(null=True),
        ),
    ]
