# Generated by Django 3.2.8 on 2021-10-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ad_is_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveads',
            options={'ordering': ['is_archive']},
        ),
    ]
