# Generated by Django 3.2.8 on 2021-10-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_archiveads_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveads',
            options={},
        ),
    ]
