# Generated by Django 3.2.8 on 2021-11-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_archiveads_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='itn',
            field=models.CharField(default='000000000', max_length=100, verbose_name='ИНН'),
        ),
    ]
