# Generated by Django 3.2.8 on 2021-11-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
