# Generated by Django 3.2.8 on 2021-11-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_archive',
            field=models.BooleanField(null=True, verbose_name='Продано'),
        ),
    ]
