# Generated by Django 3.2.8 on 2021-11-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211111_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(default='images/avatars/default-avatar.jpg', upload_to='images/avatars/'),
        ),
    ]
