# Generated by Django 3.2.8 on 2021-11-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_seller_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(default='images/ads/default-product.jpg', upload_to='images/ads/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ad', verbose_name='Продавец')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
