# Generated by Django 3.2.8 on 2021-11-28 13:54

from django.db import migrations, models
import main.validator


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='itn',
            field=models.CharField(default='000000000', max_length=11, validators=[main.validator.validate_itn], verbose_name='ИНН'),
        ),
    ]
