# Generated by Django 3.2.8 on 2021-12-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_seller_itn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpicture',
            name='image',
            field=models.ImageField(default='images/avatars/default-avatar.jpg', upload_to='images/ads/'),
        ),
    ]
