# Generated by Django 3.2.8 on 2021-12-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.TextField(blank=True, help_text='Номер телефона пользователя'),
        ),
    ]
