# Generated by Django 3.2.8 on 2022-01-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
