# Generated by Django 3.2.8 on 2022-01-06 16:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_ad_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
