# Generated by Django 3.2.8 on 2022-01-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_ad_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='tags',
        ),
    ]
