# Generated by Django 3.2.8 on 2022-01-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_ad_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='tag',
        ),
    ]
