# Generated by Django 3.2.8 on 2022-01-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_ad_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
