# Generated by Django 3.2.8 on 2022-01-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
