# Generated by Django 3.2.8 on 2022-01-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20220116_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpicture',
            name='test_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
