# Generated by Django 3.2.8 on 2022-01-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_adpicture_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpicture',
            name='test_field',
            field=models.CharField(blank=True, default='pararara', max_length=100, null=True),
        ),
    ]
