# Generated by Django 3.2.8 on 2022-01-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_adpicture_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpicture',
            name='image',
            field=models.ImageField(default='images/avatars/default-avatar.jpg', upload_to='images/avatars/'),
        ),
    ]
