# Generated by Django 3.2.8 on 2022-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_adpicture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adpicture',
            name='test_field',
        ),
        migrations.AlterField(
            model_name='adpicture',
            name='image',
            field=models.ImageField(default='images/ads/default-product.jpg', upload_to='images/ads/'),
        ),
    ]
