# Generated by Django 3.2.8 on 2022-01-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20220129_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adpicture',
            name='name',
        ),
    ]
