# Generated by Django 3.2.8 on 2022-02-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_adpicture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpicture',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='main.ad', verbose_name='Объявление'),
        ),
    ]
