# Generated by Django 3.2.8 on 2022-02-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_adpicture_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpicture',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_picture', to='main.ad', verbose_name='Объявление'),
        ),
    ]
