# Generated by Django 3.2.8 on 2022-02-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_adpicture_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpicture',
            name='test_field',
            field=models.CharField(default='abracadabra', max_length=100),
        ),
    ]
