# Generated by Django 3.2.8 on 2022-02-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_adpicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpicture',
            name='image',
            field=models.ImageField(default='images/ads/default-product.jpg', upload_to='images/ads/'),
        ),
    ]
